import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "./context/AuthProvider";
import { Suspense } from "react";
import Loading from "./components/loading/loading";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className={inter.className}>
        <Suspense fallback={<Loading />}>
          <AuthProvider>{children}</AuthProvider>
          <Toaster />
        </Suspense>
      </body>
    </html>
  );
}
